"""added uuid

Revision ID: 2365da178316
Revises: 5994e2446093
Create Date: 2020-01-23 00:48:48.855336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2365da178316'
down_revision = '5994e2446093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('api_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_match_api_token'), 'match', ['api_token'], unique=True)
    op.add_column('telescope', sa.Column('api_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_telescope_api_token'), 'telescope', ['api_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telescope_api_token'), table_name='telescope')
    op.drop_column('telescope', 'api_token')
    op.drop_index(op.f('ix_match_api_token'), table_name='match')
    op.drop_column('match', 'api_token')
    # ### end Alembic commands ###
