"""added z to galaxies

Revision ID: 5994e2446093
Revises: 5db8be66cf18
Create Date: 2020-01-21 21:40:29.507644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5994e2446093'
down_revision = '5db8be66cf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galaxy', sa.Column('z', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galaxy', 'z')
    # ### end Alembic commands ###
