"""add match

Revision ID: 9d1d4b8fcfda
Revises: b1e88aed84af
Create Date: 2020-01-20 19:24:32.985276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1d4b8fcfda'
down_revision = 'b1e88aed84af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('telescope_id', sa.Integer(), nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_observed', sa.DateTime(), nullable=True),
    sa.Column('date_confirmed', sa.DateTime(), nullable=True),
    sa.Column('source_found', sa.Boolean(), nullable=True),
    sa.Column('source_ra', sa.Float(), nullable=True),
    sa.Column('source_de', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['galaxy_id'], ['galaxy.galaxy_id'], ),
    sa.ForeignKeyConstraint(['telescope_id'], ['telescope.telescope_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
