"""add user, telescope, galaxy, events

Revision ID: b1e88aed84af
Revises: 2ff070d830d0
Create Date: 2020-01-20 19:13:27.017605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e88aed84af'
down_revision = '2ff070d830d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('gracedb_id', sa.String(length=12), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('dist', sa.Float(), nullable=True),
    sa.Column('dist_err', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('assigned', sa.Integer(), nullable=True),
    sa.Column('possible', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('gracedb_id')
    )
    op.create_table('galaxy',
    sa.Column('galaxy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('de', sa.Float(), nullable=True),
    sa.Column('dist', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('galaxy_id')
    )
    op.add_column('telescope', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('telescope', sa.Column('camera_model', sa.String(length=64), nullable=True))
    op.add_column('telescope', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('telescope', sa.Column('fov', sa.Float(), nullable=True))
    op.add_column('telescope', sa.Column('location_alias', sa.String(length=64), nullable=True))
    op.add_column('telescope', sa.Column('robotic', sa.Boolean(), nullable=True))
    op.add_column('telescope', sa.Column('software', sa.String(length=64), nullable=True))
    op.add_column('telescope', sa.Column('time_to_nineteen', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('api_token', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_api_token'), 'user', ['api_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_token'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'date_created')
    op.drop_column('user', 'api_token')
    op.drop_column('user', 'active')
    op.drop_column('telescope', 'time_to_nineteen')
    op.drop_column('telescope', 'software')
    op.drop_column('telescope', 'robotic')
    op.drop_column('telescope', 'location_alias')
    op.drop_column('telescope', 'fov')
    op.drop_column('telescope', 'date_created')
    op.drop_column('telescope', 'camera_model')
    op.drop_column('telescope', 'active')
    op.drop_table('galaxy')
    op.drop_table('event')
    # ### end Alembic commands ###
