"""fixed

Revision ID: bafcd62cf5fb
Revises: 2365da178316
Create Date: 2020-01-23 01:05:44.600462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafcd62cf5fb'
down_revision = '2365da178316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_api_token', table_name='match')
    op.create_index(op.f('ix_match_api_token'), 'match', ['api_token'], unique=False)
    op.drop_index('ix_telescope_api_token', table_name='telescope')
    op.create_index(op.f('ix_telescope_api_token'), 'telescope', ['api_token'], unique=False)
    op.drop_index('ix_user_api_token', table_name='user')
    op.create_index(op.f('ix_user_api_token'), 'user', ['api_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_token'), table_name='user')
    op.create_index('ix_user_api_token', 'user', ['api_token'], unique=True)
    op.drop_index(op.f('ix_telescope_api_token'), table_name='telescope')
    op.create_index('ix_telescope_api_token', 'telescope', ['api_token'], unique=True)
    op.drop_index(op.f('ix_match_api_token'), table_name='match')
    op.create_index('ix_match_api_token', 'match', ['api_token'], unique=True)
    # ### end Alembic commands ###
