FROM tiangolo/uwsgi-nginx-flask:python3.7
RUN python -m pip install healpy pygcn ligo.skymap astropy pyephem pandas
RUN python -m pip install mysql-connector mysqlclient
RUN python -m pip install sqlalchemy pymysql
RUN python -m pip install flask-wtf flask-sqlalchemy flask-migrate flask-login flask-mail pyjwt flask-bootstrap flask-moment flask-admin flask-security
